"""
Data schemas for FinVL-MAS.
Defines tri-modal aligned data structures: chart images, text, and time-series.

The core unit is a `DecisionSample` — a single point-in-time snapshot containing
all three modalities aligned to a decision date, stored as JSON for reproducibility.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd


# ──────────────────────────────────────────────
# Modality 1: Time-Series (OHLCV + Indicators)
# ──────────────────────────────────────────────

@dataclass
class OHLCVBar:
    """Single OHLCV bar."""
    date: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    adj_close: Optional[float] = None


@dataclass
class TimeSeriesData:
    """
    Multivariate time-series data for a lookback window.
    All arrays have shape [lookback_window].
    """
    dates: List[str]
    open: List[float]
    high: List[float]
    low: List[float]
    close: List[float]
    volume: List[float]
    # Technical indicators (computed, not raw)
    sma_5: Optional[List[float]] = None
    sma_20: Optional[List[float]] = None
    rsi_14: Optional[List[float]] = None
    macd: Optional[List[float]] = None
    macd_signal: Optional[List[float]] = None
    bb_upper: Optional[List[float]] = None
    bb_lower: Optional[List[float]] = None
    atr_14: Optional[List[float]] = None
    # Returns
    daily_returns: Optional[List[float]] = None

    @property
    def length(self) -> int:
        return len(self.dates)


# ──────────────────────────────────────────────
# Modality 2: Chart Image (rendered visualization)
# ──────────────────────────────────────────────

@dataclass
class ChartImageData:
    """
    Rendered chart image metadata.
    The image itself is stored as a file; this struct holds the path and metadata.
    """
    image_path: str  # relative to data root
    chart_type: str = "candlestick_volume"  # candlestick_volume, line_ma, etc.
    lookback_bars: int = 60
    overlays: List[str] = field(default_factory=list)  # ["sma_5", "sma_20", "bollinger"]
    width: int = 1024
    height: int = 768
    dpi: int = 150
    # Axis metadata (for coordinate mapping)
    price_min: float = 0.0
    price_max: float = 0.0
    date_start: str = ""
    date_end: str = ""


# ──────────────────────────────────────────────
# Modality 3: Textual Context
# ──────────────────────────────────────────────

@dataclass
class NewsItem:
    """A single news article or headline."""
    date: str
    headline: str
    summary: str = ""
    source: str = ""
    sentiment: Optional[float] = None  # -1.0 (bearish) to 1.0 (bullish)
    relevance: float = 0.5  # 0-1 relevance score


@dataclass
class FilingItem:
    """SEC filing excerpt (10-K, 10-Q, 8-K)."""
    date: str
    filing_type: str  # "10-K", "10-Q", "8-K"
    section: str = ""  # e.g. "Item 7 - MD&A"
    content: str = ""
    fiscal_period: str = ""  # e.g. "Q3 2022", "FY 2022"


@dataclass
class AnalystReport:
    """Analyst/research report summary."""
    date: str
    source: str = ""  # "zacks", "morningstar", etc.
    rating: str = ""  # "buy", "hold", "sell", "strong_buy"
    target_price: Optional[float] = None
    summary: str = ""


@dataclass
class TextualContext:
    """
    All textual context available at a decision point.
    Follows point-in-time constraint: only data published before decision_date.
    """
    news: List[NewsItem] = field(default_factory=list)
    filings: List[FilingItem] = field(default_factory=list)
    analyst_reports: List[AnalystReport] = field(default_factory=list)
    # Aggregated text summary (generated by pipeline)
    combined_summary: str = ""

    @property
    def has_text(self) -> bool:
        return bool(self.news or self.filings or self.analyst_reports or self.combined_summary)


# ──────────────────────────────────────────────
# Tri-Modal Aligned Sample
# ──────────────────────────────────────────────

@dataclass
class DecisionSample:
    """
    A single tri-modal aligned decision sample.
    This is the fundamental data unit for FinVL-MAS.
    
    All three modalities are aligned to the same decision_date:
    - time_series: OHLCV + indicators up to (and including) decision_date
    - chart_image: rendered from the same OHLCV window
    - textual_context: news/filings published before decision_date
    
    The label (if available) is the forward return computed AFTER decision_date.
    """
    # Identifiers
    sample_id: str = ""
    asset: str = ""
    decision_date: str = ""
    
    # Three modalities
    time_series: Optional[TimeSeriesData] = None
    chart_image: Optional[ChartImageData] = None
    textual_context: Optional[TextualContext] = None
    
    # Label (for training/evaluation)
    label: Optional[Dict[str, Any]] = None  # {"forward_return_1d": 0.02, "direction": "up", ...}
    
    # Metadata
    market: str = ""
    sector: str = ""
    lookback_window: int = 60
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a JSON-compatible dict."""
        import dataclasses
        def _convert(obj):
            if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
                return {k: _convert(v) for k, v in dataclasses.asdict(obj).items()}
            elif isinstance(obj, list):
                return [_convert(i) for i in obj]
            elif isinstance(obj, dict):
                return {k: _convert(v) for k, v in obj.items()}
            elif isinstance(obj, (np.integer,)):
                return int(obj)
            elif isinstance(obj, (np.floating,)):
                return float(obj)
            elif isinstance(obj, np.ndarray):
                return obj.tolist()
            return obj
        return _convert(self)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "DecisionSample":
        """Deserialize from a dict."""
        ts_data = d.get("time_series")
        ts = TimeSeriesData(**ts_data) if ts_data else None
        
        ci_data = d.get("chart_image")
        ci = ChartImageData(**ci_data) if ci_data else None
        
        tc_data = d.get("textual_context")
        tc = None
        if tc_data:
            news = [NewsItem(**n) for n in tc_data.get("news", [])]
            filings = [FilingItem(**f) for f in tc_data.get("filings", [])]
            reports = [AnalystReport(**r) for r in tc_data.get("analyst_reports", [])]
            tc = TextualContext(
                news=news, filings=filings, analyst_reports=reports,
                combined_summary=tc_data.get("combined_summary", ""),
            )
        
        return cls(
            sample_id=d.get("sample_id", ""),
            asset=d.get("asset", ""),
            decision_date=d.get("decision_date", ""),
            time_series=ts,
            chart_image=ci,
            textual_context=tc,
            label=d.get("label"),
            market=d.get("market", ""),
            sector=d.get("sector", ""),
            lookback_window=d.get("lookback_window", 60),
            metadata=d.get("metadata", {}),
        )


# ──────────────────────────────────────────────
# Dataset Container
# ──────────────────────────────────────────────

@dataclass
class FinVLDataset:
    """
    A collection of tri-modal aligned samples with split info.
    Stored as a JSONL file (one JSON object per line) + image directory.
    """
    samples: List[DecisionSample] = field(default_factory=list)
    split: str = ""  # "train", "valid", "test"
    market: str = ""
    assets: List[str] = field(default_factory=list)
    date_range: tuple = ("", "")
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __len__(self) -> int:
        return len(self.samples)

    def save_jsonl(self, path: str):
        """Save dataset as JSONL (one sample per line)."""
        import json, os
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w") as f:
            for s in self.samples:
                f.write(json.dumps(s.to_dict(), ensure_ascii=False) + "\n")

    @classmethod
    def load_jsonl(cls, path: str) -> "FinVLDataset":
        """Load dataset from JSONL."""
        import json
        samples = []
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    samples.append(DecisionSample.from_dict(json.loads(line)))
        ds = cls(samples=samples)
        if samples:
            ds.assets = list(set(s.asset for s in samples))
            ds.date_range = (samples[0].decision_date, samples[-1].decision_date)
        return ds


# ──────────────────────────────────────────────
# Legacy helpers
# ──────────────────────────────────────────────

def validate_ohlcv_df(df: pd.DataFrame) -> pd.DataFrame:
    """Validate and clean an OHLCV DataFrame."""
    required = {"open", "high", "low", "close", "volume"}
    cols_lower = {c.lower(): c for c in df.columns}
    missing = required - set(cols_lower.keys())
    if missing:
        raise ValueError(f"OHLCV DataFrame missing columns: {missing}")

    rename_map = {}
    for std_name, orig_name in cols_lower.items():
        if std_name in required and orig_name != std_name:
            rename_map[orig_name] = std_name
    if rename_map:
        df = df.rename(columns=rename_map)

    if not isinstance(df.index, pd.DatetimeIndex):
        date_col = cols_lower.get("date") or cols_lower.get("datetime")
        if date_col and date_col in df.columns:
            df = df.set_index(pd.to_datetime(df[date_col]))
            df = df.drop(columns=[date_col], errors="ignore")
        else:
            df.index = pd.to_datetime(df.index)

    df = df.sort_index()
    for col in ["open", "high", "low", "close"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df["volume"] = pd.to_numeric(df["volume"], errors="coerce").fillna(0)
    df = df.dropna(subset=["open", "high", "low", "close"])
    return df
